Screen:
    name: "MainScreen"
    FloatLayout:
        
            
        
        MDLabel:
            text: "TubeOder"
            font_style: 'H4'
            pos_hint : {'center_x':0.5 ,'center_y':0.9}
            halign :"center"
            
        MDLabel:
            text: "Powered by AnuSav"
            font_style: 'H6'
            pos_hint : {'center_x':0.5 ,'center_y':0.85}
            halign :"center"    

        MDTextField:
            id:username_text_fied
            hint_text: "Enter YouTube Link"
            helper_text:"forget"
            pos_hint : {'center_x':0.5 ,'center_y':0.7}
            width: 500
            size_hint: (0.7,0.1)
        	helper_text: 'Required'

                   
        MDRectangleFlatButton:
            text: "Convert"
            pos_hint : {'center_x':0.5 ,'center_y':0.2}
            text_color: 0, 0, 1, 1
            md_bg_color: 1, 1, 0, 1
            on_release: app.submit()
            width: 500
        AsyncImage:
            id:imagexpa
            size_hint_y: None
            source: 'https://blogger.googleusercontent.com/img/a/AVvXsEiZzdfR3bUbLv_CKG4Xs8wyQ3s-heibvk7azhRX_Hds1aah5owybHxIFveArAr6HtK00ozA_agvpl0fvXcu1dN3QdBkVgt6CNCh0LEEPV6-6hPc1GQPFZRt4CvB2al56scQ7fgHI3grEFk0a4j1WM_aVDZ6V-Pklivm_RNRrZKN8ym_bsIWs-IjiHenWQ=s500'
            width: 200
            allow_stretch: True
            pos_hint : {'center_x':0.5 ,'center_y':0.5}
        MDLabel:
            id:titlexpa
            text: "TUBEODER TITLE"
            pos_hint : {'center_x':0.5 ,'center_y':0.35}
            halign :"center"
        MDFloatingActionButton:
            id: disabled_button
            disabled: True
            icon:'arrow-right'
            md_bg_color:app.theme_cls.primary_color
            pos_hint: {'center_x':0.9,'center_y':0.1}
            user_font_size: '45sp'
            on_press: root.manager.current = 'Conv'
       
       
            
            



